# Project: ADTVoting
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o BAdmin.o BLogin.o BUser.o
LINKOBJ  = main.o BAdmin.o BLogin.o BUser.o
LIBS     = -L"C:/Program Files/DevCPP/Dev-Cpp/MinGW64/lib" -L"C:/Program Files/DevCPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files/DevCPP/Dev-Cpp/MinGW64/include" -I"C:/Program Files/DevCPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files/DevCPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files/DevCPP/Dev-Cpp/MinGW64/include" -I"C:/Program Files/DevCPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files/DevCPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files/DevCPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ADTVoting.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

BAdmin.o: BAdmin.c
	$(CC) -c BAdmin.c -o BAdmin.o $(CFLAGS)

BLogin.o: BLogin.c
	$(CC) -c BLogin.c -o BLogin.o $(CFLAGS)

BUser.o: BUser.c
	$(CC) -c BUser.c -o BUser.o $(CFLAGS)
